FROM quay.io.fedora/fedora:latest

# Install FlightGear and Subversion
RUN dnf install -y flightgear subversion && \
    dnf clean all

RUN svn co https://svn.code.sf.net/p/flightgear/fgaddon/trunk/Aircraft/V22-Osprey /usr/share/games/flightgear/Aircraft/V22-Osprey

ENTRYPOINT ["fgfs", "--aircraft=V22-Osprey", "--heading=0", "--lat=38.781470", "--lon=-104.685819"]