# Start with a standard RHEL Image Mode image for 9.4
FROM registry.redhat.io/rhel9/rhel-bootc:9.4

RUN sudo subscription-manager repos --enable codeready-builder-for-rhel-9-aarch64-rpms || \
    dnf config-manager --set-enabled codeready-builder-for-rhel-9-aarch64-rpms 

RUN dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
# Install Weston (Display/Streamer) and SVN
RUN dnf install -y weston podman && \
    dnf clean all

# Setup folders to store microshift images for offline image creation
ENV IMAGE_STORAGE_DIR=/usr/lib/containers/storage
ENV IMAGE_LIST_FILE=${IMAGE_STORAGE_DIR}/image-list.txt

# Setup NVIDIA repositories
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | tee /etc/yum.repos.d/nvidia-container-toolkit.repo
RUN curl -s -L https://repo.download.nvidia.com/jetson/rhel-9.4/jp6.1/nvidia-l4t.repo | tee /etc/yum.repos.d/nvidia-l4t.repo

# Setup NVIDIA Jetson Orin support packages
RUN dnf -y install nvidia-jetpack-kmod nvidia-jetpack-all nvidia-container-toolkit &&\
    dnf clean all

# Prevent the kernel from being updated
RUN echo "exclude=kernel* kmod-kvdo" >> /etc/yum.conf

# Set microshift version to install
ARG USHIFT_VER=4.18

# Install microshift
RUN dnf config-manager \
        --set-enabled rhocp-${USHIFT_VER}-for-rhel-9-$(uname -m)-rpms \
        --set-enabled fast-datapath-for-rhel-9-$(uname -m)-rpms
RUN dnf install -y firewalld microshift microshift-release-info && \
    systemctl enable microshift && \
    dnf clean all

# Create a default 'redhat' user with the specified password.
# Add it to the 'wheel' group to allow for running sudo commands.
ARG USER_PASSWD
ARG USER_NAME
RUN if [ -z "${USER_PASSWD}" ] ; then \
        echo USER_PASSWD is a mandatory build argument && exit 1 ; \
    fi
RUN useradd -m -d /var/home/redhat -G wheel redhat && \
    echo "redhat:${USER_PASSWD}" | chpasswd || true

# Mandatory firewall configuration for microshift
RUN firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1

# Create a systemd unit to recursively make the root filesystem subtree
# shared as required by OVN images
COPY microshift-make-rshared.service /etc/systemd/system/microshift-make-rshared.service
RUN systemctl enable microshift-make-rshared.service

# Pull the container images into /usr/lib/containers/storage:
# - Each image goes into a separate sub-directory
# - Sub-directories are named after the image reference string SHA
# - An image list file maps image references to their name SHA
# hadolint ignore=DL4006
RUN --mount=type=secret,id=pullsecret,dst=/run/secrets/pull-secret.json \
    images="$(jq -r ".images[]" /usr/share/microshift/release/release-"$(uname -m)".json)" ; \
    mkdir -p "${IMAGE_STORAGE_DIR}" ; \
    for img in ${images} ; do \
        sha="$(echo "${img}" | sha256sum | awk '{print $1}')" ; \
        skopeo copy --all --preserve-digests \
            --authfile /run/secrets/pull-secret.json \
            "docker://${img}" "dir:$IMAGE_STORAGE_DIR/${sha}" ; \
        echo "${img},${sha}" >> "${IMAGE_LIST_FILE}" ; \
    done

# Install a systemd drop-in unit to address the problem with image upgrades
# overwriting the container images in additional store. The workaround is to
# copy the images from the pre-loaded to the main container storage.
# In this case, it is not necessary to update /etc/containers/storage.conf with
# the additional store path.
# See https://issues.redhat.com/browse/RHEL-75827
COPY microshift-copy-images /usr/bin/microshift-copy-images
RUN chmod 755 /usr/bin/microshift-copy-images && \
    mkdir -p /usr/lib/systemd/system/microshift.service.d

COPY microshift-copy-images.conf /usr/lib/systemd/system/microshift.service.d/microshift-copy-images.conf

# Create a service to regenerate the cdi mappings for the NVIDIA Jetson Orin iGPU
COPY nvidia-cdi.service /usr/lib/systemd/system/nvidia-cdi.service
RUN systemctl enable nvidia-cdi.service

# Mandatory firewall configuration for microshift (and VNC)
RUN firewall-offline-cmd --zone=public --add-port=22/tcp && \
    firewall-offline-cmd --zone=public --add-port=5900/tcp && \
    firewall-offline-cmd --zone=trusted --add-source=10.42.0.0/16 && \
    firewall-offline-cmd --zone=trusted --add-source=169.254.169.1

# Set the redhat user to be in the video group to allow rootless use of the iGPU
RUN usermod -a -G video redhat

# Create a dedicated non-root user to run the simulator
RUN useradd -m -s /bin/bash flightuser && \
    usermod -aG video,render flightuser 
# (Adding to video/render groups ensures the user has permission to use the Jetson's GPU)

# Copy the systemd service file into the container image
COPY start-simulator.sh /usr/local/bin/start-simulator.sh
RUN chmod +x /usr/local/bin/start-simulator.sh
COPY flightgear.service /etc/systemd/system/flightgear.service

# Enable the service so it runs automatically on boot
RUN systemctl enable flightgear.service
RUN subscription-manager clean
ARG RH_REG_USERNAME
ARG RH_REG_PASSWD
RUN subscription-manager register --username "${RH_REG_USERNAME}" --password "${RH_REG_PASSWD}" --auto-attach
# RUN dnf config-manager addrepo --from-repofile=https://rpm.flightctl.io/flightctl-fedora.repo
RUN subscription-manager repos --enable rhacm-2.13-for-rhel-9-aarch64-rpms
RUN dnf install -y flightctl-ctl
# Optionnal - Add RHEM agents for integration with Red Hat Edge Manager
RUN dnf -y copr enable @redhat-et/flightctl && \
    dnf -y install python3-pip && pip install podman-compose && \
#    dnf -y install flightctl-agent-1.0.2-1.el9.aarch64 && \
    dnf -y clean all && \
    systemctl enable flightctl-agent.service

# RUN podman login quay.io --username "${USER_NAME}" --password "${USER_PASSWD}"
ARG FLIGHTCTL_PASSWD
RUN flightctl login --username admin --password "${FLIGHTCTL_PASSWD}" api.modern-recon.apps.cluster-p5gmw.dynamic.redhatworkshops.io 
RUN flightctl certificate request --signer=enrollment --expiration=365d --output=embedded > config.yaml
COPY config.yaml /etc/flightctl/config.yaml